#!/usr/bin/env python3
"""Generate an auditable activity map for this repository.

Public reports are derived from a committed HEAD snapshot. Working-copy timestamps
can be emitted separately for diagnosis, but never affect committed scores.
"""

from __future__ import annotations

import argparse
import dataclasses
import datetime as dt
import html
import json
import math
from pathlib import Path
import subprocess
import sys
from typing import Any, Iterable
from zoneinfo import ZoneInfo


ROOT = Path(__file__).resolve().parents[1]
CONFIG_PATH = ROOT / "repo-activity.json"
GENERATED_NOTICE = "Generated by `python tools/repo_activity.py --write`; do not edit by hand."
ROOT_MARKER_START = "<!-- repo-activity:start -->"
ROOT_MARKER_END = "<!-- repo-activity:end -->"
MANAGED_PUBLICATION_PATHS = {
    "README.md",
    "data/README.md",
    "docs/README.md",
    "erasave/README.md",
    "framework/README.md",
    "quest_select_design/README.md",
    "recipes/README.md",
    "repo-activity.json",
    "tests/test_entrypoint_links.py",
    "tests/test_repo_activity.py",
    "tools/README.md",
    "tools/repo_activity.py",
}


@dataclasses.dataclass
class FileActivity:
    path: str
    size_bytes: int
    category: str
    created_at: dt.datetime | None = None
    updated_at: dt.datetime | None = None
    touches: int = 0
    additions: int = 0
    deletions: int = 0
    active_days: set[str] = dataclasses.field(default_factory=set)
    recent_touches: int = 0
    score: float = 0.0

    @property
    def top_level(self) -> str:
        return self.path.split("/", 1)[0]


def run_git(*args: str) -> str:
    result = subprocess.run(
        ["git", *args], cwd=ROOT, check=True, stdout=subprocess.PIPE,
        stderr=subprocess.PIPE, text=True, encoding="utf-8", errors="replace"
    )
    return result.stdout


def load_config(path: Path = CONFIG_PATH) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def parse_iso(value: str) -> dt.datetime:
    return dt.datetime.fromisoformat(value.replace("Z", "+00:00"))


def percentile(values: Iterable[float], fraction: float = 0.95) -> float:
    ordered = sorted(values)
    if not ordered:
        return 1.0
    index = min(len(ordered) - 1, max(0, math.ceil(len(ordered) * fraction) - 1))
    return max(float(ordered[index]), 1.0)


def normalized_log(value: float, cap: float) -> float:
    return min(1.0, math.log1p(max(0.0, value)) / math.log1p(max(1.0, cap)))


def category_for(path: str, config: dict[str, Any]) -> str:
    for category in config["categories"]:
        if any(path.startswith(prefix) for prefix in category["prefixes"]):
            return category["name"]
    return "Repository root"


def is_excluded(path: str, config: dict[str, Any]) -> bool:
    return any(path.startswith(prefix) for prefix in config.get("exclude_prefixes", []))


def tracked_files(config: dict[str, Any], revision: str) -> dict[str, FileActivity]:
    raw = subprocess.run(
        ["git", "ls-tree", "-r", "-l", "-z", revision], cwd=ROOT, check=True,
        stdout=subprocess.PIPE, stderr=subprocess.PIPE
    ).stdout
    files: dict[str, FileActivity] = {}
    for row in raw.split(b"\0"):
        if not row:
            continue
        metadata, raw_path = row.split(b"\t", 1)
        parts = metadata.split()
        size = 0 if parts[-1] == b"-" else int(parts[-1])
        path = raw_path.decode("utf-8", errors="replace").replace("\\", "/")
        if not is_excluded(path, config):
            files[path] = FileActivity(path, size, category_for(path, config))
    return files


def commit_records(config: dict[str, Any], files: dict[str, FileActivity], revision: str) -> list[dict[str, Any]]:
    tz = ZoneInfo(config["timezone"])
    marker = "@@COMMIT@@"
    output = run_git(
        "log", "--reverse", "--date=iso-strict", f"--format={marker}%H|%aI",
        "--numstat", "--no-renames", revision
    )
    commits: list[dict[str, Any]] = []
    current: dict[str, Any] | None = None
    for line in output.splitlines():
        if line.startswith(marker):
            sha, stamp = line[len(marker):].split("|", 1)
            current = {"sha": sha, "at": parse_iso(stamp).astimezone(tz), "files": []}
            commits.append(current)
            continue
        if not current or not line or "\t" not in line:
            continue
        additions, deletions, path = line.split("\t", 2)
        path = path.replace("\\", "/")
        if path not in files:
            continue
        add = 0 if additions == "-" else int(additions)
        delete = 0 if deletions == "-" else int(deletions)
        current["files"].append((path, add, delete))
        file = files[path]
        file.created_at = file.created_at or current["at"]
        file.updated_at = current["at"]
        file.touches += 1
        file.additions += add
        file.deletions += delete
        file.active_days.add(current["at"].date().isoformat())
    return commits


def compute_scores(config: dict[str, Any], files: dict[str, FileActivity], latest: dt.datetime) -> None:
    touched = [file for file in files.values() if file.updated_at]
    touch_cap = percentile(file.touches for file in touched)
    size_cap = percentile(file.size_bytes / 1024 for file in files.values())
    repo_start = min(file.created_at for file in touched if file.created_at)
    repo_days = max(1.0, (latest - repo_start).total_seconds() / 86400)
    recent_start = latest - dt.timedelta(days=config["recent_burst_days"])
    recent_cap = percentile(
        sum(1 for day in file.active_days if dt.date.fromisoformat(day) >= recent_start.date())
        for file in touched
    )
    weights = config["weights"]
    size_floor = config["size_weight"]["floor"]
    size_ceiling = config["size_weight"]["ceiling"]
    for file in touched:
        age_days = max(0.0, (latest - file.updated_at).total_seconds() / 86400)
        recency = 2 ** (-age_days / config["recency_half_life_days"])
        touch = normalized_log(file.touches, touch_cap)
        span_days = max(0.0, (file.updated_at - file.created_at).total_seconds() / 86400)
        lifespan = min(1.0, math.log1p(span_days) / math.log1p(repo_days))
        file.recent_touches = sum(
            1 for day in file.active_days if dt.date.fromisoformat(day) >= recent_start.date()
        )
        burst = normalized_log(file.recent_touches, recent_cap)
        size_norm = normalized_log(file.size_bytes / 1024, size_cap)
        size_weight = size_floor + (size_ceiling - size_floor) * size_norm
        base = (
            weights["recency"] * recency
            + weights["touch_frequency"] * touch
            + weights["active_lifespan"] * lifespan
            + weights["recent_burst"] * burst
        )
        file.score = round(100 * base * size_weight, 2)


def era_for(day: str, config: dict[str, Any]) -> str:
    for era in config["eras"]:
        if era["start"] <= day <= era["end"]:
            return era["id"]
    return f"later-{day[:7]}"


def report_eras(config: dict[str, Any], files: dict[str, FileActivity]) -> list[dict[str, str]]:
    eras = [dict(era) for era in config["eras"]]
    known = {era["id"] for era in eras}
    later: dict[str, set[str]] = {}
    for file in files.values():
        for stamp in (file.created_at, file.updated_at):
            if not stamp:
                continue
            day = stamp.date().isoformat()
            era_id = era_for(day, config)
            if era_id not in known:
                later.setdefault(era_id, set()).add(day)
    for era_id, days in sorted(later.items(), key=lambda item: min(item[1])):
        month = era_id.removeprefix("later-")
        eras.append({
            "id": era_id,
            "label": f"Later work ({month})",
            "start": min(days),
            "end": max(days),
        })
    return eras


def aggregate(config: dict[str, Any], files: dict[str, FileActivity], commits: list[dict[str, Any]]) -> dict[str, Any]:
    daily: dict[str, dict[str, Any]] = {}
    for commit in commits:
        day = commit["at"].date().isoformat()
        row = daily.setdefault(day, {"commits": 0, "files": set(), "touches": 0, "additions": 0, "deletions": 0, "weighted_kb": 0.0})
        row["commits"] += 1
        for path, additions, deletions in commit["files"]:
            row["files"].add(path)
            row["touches"] += 1
            row["additions"] += additions
            row["deletions"] += deletions
            row["weighted_kb"] += math.log2(files[path].size_bytes / 1024 + 1)
    for row in daily.values():
        row["files"] = len(row["files"])
        row["activity"] = round(row["commits"] + math.log1p(row["additions"] + row["deletions"]) + row["weighted_kb"], 2)

    directory: dict[str, dict[str, Any]] = {}
    category: dict[str, dict[str, Any]] = {}
    matrix: dict[tuple[str, str], dict[str, Any]] = {}
    for file in files.values():
        if not file.updated_at:
            continue
        for key, target in ((file.top_level, directory), (file.category, category)):
            row = target.setdefault(key, {"files": 0, "size_bytes": 0, "touches": 0, "additions": 0, "deletions": 0, "active_days": set(), "score": 0.0})
            row["files"] += 1
            row["size_bytes"] += file.size_bytes
            row["touches"] += file.touches
            row["additions"] += file.additions
            row["deletions"] += file.deletions
            row["active_days"].update(file.active_days)
            row["score"] += file.score
            if target is directory:
                row["is_directory"] = "/" in file.path
        created_era = era_for(file.created_at.date().isoformat(), config)
        updated_era = era_for(file.updated_at.date().isoformat(), config)
        cell = matrix.setdefault((created_era, updated_era), {"files": 0, "size_bytes": 0, "touches": 0, "score": 0.0})
        cell["files"] += 1
        cell["size_bytes"] += file.size_bytes
        cell["touches"] += file.touches
        cell["score"] += file.score

    def finish(rows: dict[str, dict[str, Any]]) -> list[dict[str, Any]]:
        result = []
        for name, row in rows.items():
            row["name"] = name
            row["active_days"] = len(row["active_days"])
            row["size_kb"] = round(row.pop("size_bytes") / 1024, 2)
            row["score"] = round(row["score"], 2)
            result.append(row)
        return sorted(result, key=lambda item: item["score"], reverse=True)

    directories = finish(directory)
    for row in directories:
        candidate = f"{row['name']}/README.md"
        row["entrypoint"] = candidate if candidate in files else None
    return {
        "daily": [{"date": day, **daily[day]} for day in sorted(daily)],
        "directories": directories,
        "categories": finish(category),
        "period_matrix": [
            {"created_era": key[0], "updated_era": key[1], "files": value["files"],
             "size_kb": round(value["size_bytes"] / 1024, 2), "touches": value["touches"],
             "score": round(value["score"], 2)}
            for key, value in sorted(matrix.items())
        ],
    }


def readme_for(directory: str) -> str | None:
    if directory.endswith(".md") or "." in Path(directory).name:
        return None
    candidate = ROOT / directory / "README.md"
    return f"../../{directory}/README.md" if candidate.exists() else None


def serialise(config: dict[str, Any], files: dict[str, FileActivity], commits: list[dict[str, Any]], summary: dict[str, Any], revision: str) -> dict[str, Any]:
    latest = max(commit["at"] for commit in commits)
    earliest = min(commit["at"] for commit in commits)
    return {
        "schema_version": 1,
        "source": {
            "commit": revision,
            "repository_url": config["repository_url"],
            "default_branch": config["default_branch"],
            "timezone": config["timezone"],
            "first_commit_at": earliest.isoformat(),
            "last_commit_at": latest.isoformat(),
            "tracked_files": len(files),
            "commits": len(commits),
            "timestamp_policy": "Git author time: first path appearance and most recent path change. Filesystem timestamps are excluded from public scoring.",
        },
        "scoring": {
            "weights": config["weights"],
            "size_weight": config["size_weight"],
            "recency_half_life_days": config["recency_half_life_days"],
            "recent_burst_days": config["recent_burst_days"],
        },
        "eras": report_eras(config, files),
        **summary,
        "files": [
            {
                "path": file.path,
                "category": file.category,
                "size_kb": round(file.size_bytes / 1024, 2),
                "repo_created_at": file.created_at.isoformat() if file.created_at else None,
                "repo_updated_at": file.updated_at.isoformat() if file.updated_at else None,
                "touches": file.touches,
                "additions": file.additions,
                "deletions": file.deletions,
                "active_days": len(file.active_days),
                "recent_touches": file.recent_touches,
                "created_era": era_for(file.created_at.date().isoformat(), config) if file.created_at else None,
                "updated_era": era_for(file.updated_at.date().isoformat(), config) if file.updated_at else None,
                "hotspot_score": file.score,
            }
            for file in sorted(files.values(), key=lambda item: (-item.score, item.path))
        ],
    }


def markdown_report(data: dict[str, Any]) -> str:
    source = data["source"]
    lines = [
        "# Repository Hotspots", "", f"> {GENERATED_NOTICE}", "",
        f"Snapshot: `{source['commit'][:12]}` · {source['commits']} commits · {source['tracked_files']} tracked files · "
        f"{source['first_commit_at'][:10]} through {source['last_commit_at'][:10]}", "",
        "[Interactive heatmap](index.html) · [GitHub-style activity graph](activity.svg) · [Raw metrics](activity.json)", "",
        "## Hotspot directories", "",
        "| Rank | Area | Score | Files | Size KB | Touches | Active days | Entry point |",
        "|---:|---|---:|---:|---:|---:|---:|---|",
    ]
    for index, row in enumerate(data["directories"], 1):
        entry = readme_for(row["name"])
        entry_text = f"[README]({entry})" if entry else "—"
        lines.append(f"| {index} | `{row['name']}` | {row['score']:.2f} | {row['files']} | {row['size_kb']:.2f} | {row['touches']} | {row['active_days']} | {entry_text} |")
    lines += ["", "## Categories", "", "| Category | Score | Files | Size KB | Touches |", "|---|---:|---:|---:|---:|"]
    for row in data["categories"]:
        lines.append(f"| {row['name']} | {row['score']:.2f} | {row['files']} | {row['size_kb']:.2f} | {row['touches']} |")
    lines += [
        "", "## How to read this", "",
        "- `repo_created_at` is the first commit in which the current path appears.",
        "- `repo_updated_at` is the most recent commit that changes the current path.",
        "- Scores combine update recency, touch frequency, active lifespan, and recent burst activity, then apply a capped logarithmic size weight.",
        "- The temporal heatmap uses first-seen era on one axis, last-updated era on the other, size for cell area, and touches for color.",
        "- Clone-local filesystem timestamps and ignored/private files do not affect these reports.", "",
        "## Periodization", "",
    ]
    for era in data["eras"]:
        lines.append(f"- **{era['start']} → {era['end']}:** {era['label']}")
    return "\n".join(lines) + "\n"


def activity_svg(data: dict[str, Any], minimum_weeks: int) -> str:
    rows = {dt.date.fromisoformat(row["date"]): row for row in data["daily"]}
    first = min(rows)
    last = max(rows)
    start = first - dt.timedelta(days=first.weekday())
    weeks = max(minimum_weeks, math.ceil(((last - start).days + 1) / 7))
    start = last - dt.timedelta(days=last.weekday()) - dt.timedelta(weeks=weeks - 1)
    values = [row["activity"] for row in rows.values()]
    cap = percentile(values)
    colors = ["#ebedf0", "#9be9a8", "#40c463", "#30a14e", "#216e39"]
    cell, gap, left, top = 11, 3, 34, 27
    width = max(320, left + weeks * (cell + gap) + 8)
    height = top + 7 * (cell + gap) + 25
    parts = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}" role="img" aria-labelledby="title desc">',
        '<title id="title">Repository activity</title>',
        '<desc id="desc">Daily repository activity weighted by commits, churn, and current file size.</desc>',
        '<style>text{font:10px -apple-system,BlinkMacSystemFont,Segoe UI,sans-serif;fill:#57606a}.month{font-size:9px}</style>',
        '<rect width="100%" height="100%" fill="white"/>',
        '<text x="0" y="49">Mon</text><text x="0" y="77">Wed</text><text x="0" y="105">Fri</text>',
    ]
    last_month = None
    for week in range(weeks):
        week_date = start + dt.timedelta(weeks=week)
        if week_date.month != last_month:
            parts.append(f'<text class="month" x="{left + week * (cell + gap)}" y="12">{week_date.strftime("%b")}</text>')
            last_month = week_date.month
        for weekday in range(7):
            day = week_date + dt.timedelta(days=weekday)
            row = rows.get(day)
            value = row["activity"] if row else 0
            level = 0 if not row else min(4, max(1, math.ceil(value / cap * 4)))
            x, y = left + week * (cell + gap), top + weekday * (cell + gap)
            detail = "No activity" if not row else f"{row['commits']} commits, {row['files']} files, +{row['additions']}/-{row['deletions']}"
            parts.append(f'<rect x="{x}" y="{y}" width="{cell}" height="{cell}" rx="2" fill="{colors[level]}"><title>{day.isoformat()}: {html.escape(detail)}</title></rect>')
    parts.append(f'<text x="{left}" y="{height - 5}">Weighted activity · snapshot {data["source"]["commit"][:12]}</text>')
    parts.append("</svg>")
    return "\n".join(parts) + "\n"


def interactive_html(data: dict[str, Any]) -> str:
    payload = json.dumps(data, separators=(",", ":"), ensure_ascii=False).replace("</", "<\\/")
    return f'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Comfy repository activity</title>
<style>
:root{{--ink:#1f2328;--muted:#656d76;--line:#d0d7de;--panel:#f6f8fa;--hot:#216e39}}*{{box-sizing:border-box}}
body{{max-width:1180px;margin:0 auto;padding:32px 20px;font:14px/1.5 system-ui,sans-serif;color:var(--ink)}}
h1,h2{{line-height:1.2}}.lede{{color:var(--muted)}}.cards{{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:12px}}
.card,.panel{{border:1px solid var(--line);border-radius:8px;padding:16px}}.card strong{{display:block;font-size:24px}}.areas{{display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:10px}}.area{{display:block;border:1px solid var(--line);border-radius:8px;padding:12px;text-decoration:none;color:var(--ink)}}.area:hover{{border-color:#0969da;background:#f6f8fa}}.area small{{display:block;color:var(--muted)}}
.controls{{display:flex;gap:12px;align-items:center;flex-wrap:wrap;margin:18px 0}}select,input{{padding:7px;border:1px solid var(--line);border-radius:6px}}
table{{width:100%;border-collapse:collapse}}th,td{{padding:8px;border-bottom:1px solid var(--line);text-align:left}}th{{position:sticky;top:0;background:white}}
.scroll{{max-height:520px;overflow:auto}}.matrix{{display:grid;gap:4px;align-items:stretch;overflow:auto}}.cell{{min-width:105px;min-height:76px;padding:7px;border-radius:5px;color:white}}.cell.clickable{{cursor:pointer;border:0;text-align:left;font:inherit}}.cell.clickable:hover,.cell.clickable:focus{{outline:3px solid #0969da;outline-offset:-3px}}.cell.active{{outline:3px solid #24292f;outline-offset:-3px}}.sizebar{{display:block;height:5px;margin-top:5px;border-radius:3px;background:rgba(255,255,255,.72)}}
.label{{font-size:11px;color:var(--muted);padding:5px}}code{{font-size:12px}}a{{color:#0969da}}@media(max-width:700px){{body{{padding:18px 10px}}}}
</style></head><body>
<h1>Comfy repository activity</h1><p class="lede" id="snapshot"></p>
<div class="cards" id="cards"></div>
<h2>Repository hotspots</h2><p class="lede">Open each area's README when available, or its repository folder otherwise.</p><div class="areas" id="areas"></div>
<h2>Created × last-updated heatmap</h2><p class="lede">The bar reports log-scaled KB; color reports file touches. Click a cell to drill into its files.</p><div class="panel"><div class="matrix" id="matrix"></div></div>
<h2 id="hot-files">Hot files</h2><div class="controls"><label>Category <select id="category"></select></label><label>Path <input id="query" placeholder="Filter paths"></label><button id="period" hidden></button></div>
<div class="panel scroll"><table><thead><tr><th>Path</th><th>Score</th><th>KB</th><th>First seen</th><th>Updated</th><th>Touches</th></tr></thead><tbody id="files"></tbody></table></div>
<script>const D={payload};
const fmt=n=>new Intl.NumberFormat().format(n),repo=D.source.repository_url,branch=D.source.default_branch;document.querySelector('#snapshot').textContent=`HEAD ${{D.source.commit.slice(0,12)}} · ${{D.source.first_commit_at.slice(0,10)}} through ${{D.source.last_commit_at.slice(0,10)}} · ${{D.source.timezone}}`;
document.querySelector('#cards').innerHTML=[['Commits',D.source.commits],['Tracked files',D.source.tracked_files],['Hotspot areas',D.directories.length],['Active days',D.daily.length]].map(x=>`<div class="card"><strong>${{fmt(x[1])}}</strong>${{x[0]}}</div>`).join('');
document.querySelector('#areas').innerHTML=D.directories.filter(x=>x.is_directory).map(x=>{{const path=x.entrypoint||x.name,url=x.entrypoint?`${{repo}}/blob/${{branch}}/${{path}}`:`${{repo}}/tree/${{branch}}/${{path}}`;return `<a class="area" href="${{url}}"><strong>${{x.name}}</strong><small>${{x.entrypoint?'Open README':'Open folder'}} · ${{x.files}} files · ${{fmt(x.size_kb)}} KB</small></a>`}}).join('');
const eras=D.eras.map(x=>x.id), labels=Object.fromEntries(D.eras.map(x=>[x.id,x.label]));const matrix=new Map(D.period_matrix.map(x=>[x.created_era+'|'+x.updated_era,x]));const maxTouch=Math.max(...D.period_matrix.map(x=>x.touches)),maxSize=Math.max(...D.period_matrix.map(x=>x.size_kb));
const grid=document.querySelector('#matrix');grid.style.gridTemplateColumns=`150px repeat(${{eras.length}},minmax(105px,1fr))`;grid.innerHTML='<div></div>'+eras.map(x=>`<div class="label">Updated: ${{labels[x]}}</div>`).join('');
eras.forEach(c=>{{grid.insertAdjacentHTML('beforeend',`<div class="label">Created: ${{labels[c]}}</div>`);eras.forEach(u=>{{const x=matrix.get(c+'|'+u);if(!x){{grid.insertAdjacentHTML('beforeend','<div class="cell" style="background:#ebedf0"></div>');return}}const light=78-48*Math.sqrt(x.touches/maxTouch),size=Math.max(4,100*Math.log1p(x.size_kb)/Math.log1p(maxSize));grid.insertAdjacentHTML('beforeend',`<button class="cell clickable" data-created="${{c}}" data-updated="${{u}}" style="background:hsl(137 55% ${{light}}%)" title="${{x.files}} files; ${{x.size_kb}} KB; ${{x.touches}} touches; score ${{x.score}}"><b>${{x.files}} files</b><br>${{fmt(x.size_kb)}} KB<br>${{x.touches}} touches<span class="sizebar" style="width:${{size}}%"></span></button>`);}})}});
const select=document.querySelector('#category');select.innerHTML='<option value="">All categories</option>'+[...new Set(D.files.map(x=>x.category))].sort().map(x=>`<option>${{x}}</option>`).join('');
let activePeriod=null;const period=document.querySelector('#period');function render(){{const cat=select.value,q=document.querySelector('#query').value.toLowerCase();document.querySelector('#files').innerHTML=D.files.filter(x=>(!cat||x.category===cat)&&x.path.toLowerCase().includes(q)&&(!activePeriod||(x.created_era===activePeriod[0]&&x.updated_era===activePeriod[1]))).slice(0,250).map(x=>`<tr><td><a href="${{repo}}/blob/${{branch}}/${{x.path}}"><code>${{x.path}}</code></a><br><small>${{x.category}}</small></td><td>${{x.hotspot_score}}</td><td>${{x.size_kb}}</td><td>${{x.repo_created_at?.slice(0,10)||''}}</td><td>${{x.repo_updated_at?.slice(0,10)||''}}</td><td>${{x.touches}}</td></tr>`).join('')}}select.onchange=render;document.querySelector('#query').oninput=render;period.onclick=()=>{{activePeriod=null;period.hidden=true;document.querySelectorAll('.cell.active').forEach(x=>x.classList.remove('active'));render()}};document.querySelectorAll('.cell.clickable').forEach(cell=>cell.onclick=()=>{{document.querySelectorAll('.cell.active').forEach(x=>x.classList.remove('active'));cell.classList.add('active');activePeriod=[cell.dataset.created,cell.dataset.updated];period.textContent=`Clear period: ${{labels[activePeriod[0]]}} → ${{labels[activePeriod[1]]}}`;period.hidden=false;render();document.querySelector('#hot-files').scrollIntoView({{behavior:'smooth'}})}});render();</script>
</body></html>'''


def local_timestamps(files: dict[str, FileActivity]) -> dict[str, Any]:
    result = {}
    for path in files:
        candidate = ROOT / path
        if candidate.exists():
            stat = candidate.stat()
            result[path] = {
                "working_copy_created_at": dt.datetime.fromtimestamp(stat.st_ctime, dt.timezone.utc).isoformat(),
                "working_copy_updated_at": dt.datetime.fromtimestamp(stat.st_mtime, dt.timezone.utc).isoformat(),
                "warning": "Machine-local filesystem evidence; excluded from hotspot scoring.",
            }
    return result


def root_activity_block(data: dict[str, Any]) -> str:
    lines = [
        ROOT_MARKER_START,
        "## Repository activity map",
        "",
        "The map below is generated from Git history: first-seen date × last-updated date, weighted by current KB and change activity.",
        "",
        "[Explore the interactive heatmap](docs/repo-map/index.html) · [Read the hotspot report](docs/repo-map/HOTSPOTS.md) · [Inspect the raw metrics](docs/repo-map/activity.json)",
        "",
        "![GitHub-style repository activity graph](docs/repo-map/activity.svg)",
        "",
        "### Current hotspots",
        "",
        "| Area | Activity score | Files | Size KB | Start here |",
        "|---|---:|---:|---:|---|",
    ]
    for row in data["directories"]:
        readme = ROOT / row["name"] / "README.md"
        if readme.exists():
            lines.append(f"| `{row['name']}` | {row['score']:.2f} | {row['files']} | {row['size_kb']:.2f} | [README]({row['name']}/README.md) |")
    lines += ["", f"Metrics snapshot: `{data['source']['commit'][:12]}`. Regenerate with `python tools/repo_activity.py --write`.", ROOT_MARKER_END]
    return "\n".join(lines)


def replace_root_activity(readme: str, data: dict[str, Any]) -> str:
    if ROOT_MARKER_START not in readme or ROOT_MARKER_END not in readme:
        return readme
    before, remainder = readme.split(ROOT_MARKER_START, 1)
    _, after = remainder.split(ROOT_MARKER_END, 1)
    return before + root_activity_block(data) + after


def expected_outputs(config: dict[str, Any], data: dict[str, Any]) -> dict[Path, str]:
    outputs = {
        ROOT / config["outputs"]["json"]: json.dumps(data, indent=2, ensure_ascii=False) + "\n",
        ROOT / config["outputs"]["markdown"]: markdown_report(data),
        ROOT / config["outputs"]["svg"]: activity_svg(data, config["history_weeks_minimum"]),
        ROOT / config["outputs"]["html"]: interactive_html(data),
    }
    root_readme = ROOT / "README.md"
    if root_readme.exists():
        current = root_readme.read_text(encoding="utf-8")
        updated = replace_root_activity(current, data)
        if updated != current or ROOT_MARKER_START in current:
            outputs[root_readme] = updated
    return outputs


def build(config: dict[str, Any], revision: str | None = None) -> tuple[dict[str, Any], dict[str, FileActivity]]:
    revision = run_git("rev-parse", revision or "HEAD").strip()
    files = tracked_files(config, revision)
    commits = commit_records(config, files, revision)
    if not commits:
        raise RuntimeError("No commits found")
    latest = max(commit["at"] for commit in commits)
    compute_scores(config, files, latest)
    summary = aggregate(config, files, commits)
    return serialise(config, files, commits, summary, revision), files


def is_managed_publication_path(path: str) -> bool:
    path = path.replace("\\", "/")
    return path.startswith("docs/repo-map/") or path in MANAGED_PUBLICATION_PATHS


def recorded_revision() -> str | None:
    activity_path = ROOT / load_config()["outputs"]["json"]
    if not activity_path.exists():
        return None
    try:
        return json.loads(activity_path.read_text(encoding="utf-8"))["source"]["commit"]
    except (KeyError, TypeError, json.JSONDecodeError):
        return None


def publication_only_since(revision: str) -> tuple[bool, list[str]]:
    ancestor = subprocess.run(
        ["git", "merge-base", "--is-ancestor", revision, "HEAD"], cwd=ROOT
    ).returncode == 0
    if not ancestor:
        return False, ["recorded source is not an ancestor of HEAD"]
    changed = [line for line in run_git("diff", "--name-only", f"{revision}..HEAD").splitlines() if line]
    unexpected = [path for path in changed if not is_managed_publication_path(path)]
    return not unexpected, unexpected


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true", help="write the committed reports")
    mode.add_argument("--check", action="store_true", help="verify reports match HEAD")
    mode.add_argument("--local-timestamps", metavar="PATH", help="write optional machine-local timestamps")
    args = parser.parse_args(argv)
    config = load_config()
    check_revision = recorded_revision() if args.check else None
    data, files = build(config, check_revision)
    if args.local_timestamps:
        target = Path(args.local_timestamps)
        target.write_text(json.dumps(local_timestamps(files), indent=2) + "\n", encoding="utf-8")
        print(f"Wrote local timestamp diagnostics to {target}")
        return 0
    outputs = expected_outputs(config, data)
    if args.write:
        for path, content in outputs.items():
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8", newline="\n")
            print(path.relative_to(ROOT))
        return 0
    stale = []
    for path, content in outputs.items():
        if not path.exists() or path.read_text(encoding="utf-8") != content:
            stale.append(str(path.relative_to(ROOT)))
    if stale:
        print("Stale repository activity outputs:", file=sys.stderr)
        print("\n".join(f"  {path}" for path in stale), file=sys.stderr)
        return 1
    publication_ok, unexpected = publication_only_since(data["source"]["commit"])
    if not publication_ok:
        print("Repository activity snapshot is behind non-publication changes:", file=sys.stderr)
        print("\n".join(f"  {path}" for path in unexpected), file=sys.stderr)
        return 1
    print(f"Repository activity outputs match recorded snapshot {data['source']['commit'][:12]}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
